# Generated by Django 6.0.5 on 2026-05-10 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                validators=[django.core.validators.MinLengthValidator(8)]
            ),
        ),
    ]
