# Generated by Django 6.0.5 on 2026-05-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_body_mass_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="target",
            field=models.CharField(
                choices=[
                    ("weight maintenance", "Maintenance"),
                    ("gaining muscle mass", "Gaining muscle mass"),
                    ("weight loss", "Loss weight"),
                ],
                default="weight maintenance",
                max_length=20,
            ),
        ),
    ]
