# Generated by Django 6.0.5 on 2026-05-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activity_status',
            field=models.CharField(choices=[(1, 'Not active'), (2, 'Light'), (3, 'Medium'), (4, 'High'), (5, 'Very high')], default='*', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='target',
            field=models.CharField(choices=[('loss', 'Weight loss'), ('maintain', 'Maintenance'), ('gain', 'Gaining muscle mass')], default='weight maintenance', max_length=20),
        ),
    ]
